# SPDX-FileCopyrightText: 2023 Daniel Wolf <nephatrine@gmail.com>
#
# SPDX-License-Identifier: ISC

name: Build Container Image
run-name: ${{ gitea.actor }} pushed to ${{ gitea.repository }}:${{ gitea.ref_name }}
on:
  push:
  schedule:
    - cron:  '20 19 * * 3'
jobs:
  build_amd64:
    if: gitea.repository_owner == 'NephNET' && (!contains(gitea.event.head_commit.message, '#noci') || gitea.event_name == 'schedule')
    runs-on: nephnet-amd64
    steps:
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Build
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-master}
          docker build --pull -t code.nephatrine.net/nephnet/write-freely:${BRANCH}-amd64-gocache --target builder1 ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/write-freely:${BRANCH}-amd64-jscache --target builder2 ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/write-freely:${BRANCH}-amd64 ${{ gitea.workspace }}
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Push
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        run: docker push code.nephatrine.net/nephnet/write-freely:master-amd64
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: "Container Build (X86_64)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  build_i386:
    if: gitea.repository_owner == 'NephNET' && (!contains(gitea.event.head_commit.message, '#noci') || gitea.event_name == 'schedule')
    runs-on: nephnet-i386
    steps:
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Build
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-master}
          docker build --pull -t code.nephatrine.net/nephnet/write-freely:${BRANCH}-i386-gocache --target builder1 --platform linux/386 ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/write-freely:${BRANCH}-i386-jscache --target builder2 --platform linux/386 ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/write-freely:${BRANCH}-i386 --platform linux/386 ${{ gitea.workspace }}
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Push
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        run: docker push code.nephatrine.net/nephnet/write-freely:master-i386
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: "Container Build (I686)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  build_arm64:
    if: gitea.repository_owner == 'NephNET' && (!contains(gitea.event.head_commit.message, '#noci') || gitea.event_name == 'schedule')
    runs-on: nephnet-arm64
    steps:
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Build
        run: |
          export BRANCH=${GITHUB_REF##*/}
          export BRANCH=${BRANCH:-master}
          docker build --pull -t code.nephatrine.net/nephnet/write-freely:${BRANCH}-arm64v8-gocache --target builder1 ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/write-freely:${BRANCH}-arm64v8-jscache --target builder2 ${{ gitea.workspace }}
          docker build --pull -t code.nephatrine.net/nephnet/write-freely:${BRANCH}-arm64v8 ${{ gitea.workspace }}
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Push
        if: gitea.ref_name == 'master' || gitea.ref_name == ''
        run: docker push code.nephatrine.net/nephnet/write-freely:master-arm64v8
      - name: Notify Discord
        uses: https://github.com/sarisia/actions-status-discord@v1
        if: failure()
        with:
          title: "Container Build (AARCH64)"
          webhook: ${{ secrets.DISCORD_WEBHOOK_BUILD }}
  build_manifest:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_amd64, build_i386, build_arm64]
    runs-on: nephnet
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          registry: code.nephatrine.net
          username: ${{ gitea.actor }}
          password: ${{ secrets.PACKAGER_TOKEN }}
      - name: Docker Manifest
        run: |
          docker manifest create code.nephatrine.net/nephnet/write-freely:latest --amend code.nephatrine.net/nephnet/write-freely:master-amd64 --amend code.nephatrine.net/nephnet/write-freely:master-i386 --amend code.nephatrine.net/nephnet/write-freely:master-arm64v8
          docker manifest push --purge code.nephatrine.net/nephnet/write-freely:latest
  publish_amd64:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_amd64]
    runs-on: nephnet-amd64
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Push
        run: |
          docker pull code.nephatrine.net/nephnet/write-freely:master-amd64
          docker tag code.nephatrine.net/nephnet/write-freely:master-amd64 nephatrine/write-freely:latest-amd64
          docker push nephatrine/write-freely:latest-amd64
          docker rmi nephatrine/write-freely:latest-amd64
  publish_i386:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_i386]
    runs-on: nephnet-i386
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Push
        run: |
          docker pull code.nephatrine.net/nephnet/write-freely:master-i386
          docker tag code.nephatrine.net/nephnet/write-freely:master-i386 nephatrine/write-freely:latest-i386
          docker push nephatrine/write-freely:latest-i386
          docker rmi nephatrine/write-freely:latest-i386
  publish_arm64:
    if: gitea.ref_name == 'master' || gitea.ref_name == ''
    needs: [build_arm64]
    runs-on: nephnet-arm64
    steps:
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Push
        run: |
          docker pull code.nephatrine.net/nephnet/write-freely:master-arm64v8
          docker tag code.nephatrine.net/nephnet/write-freely:master-arm64v8 nephatrine/write-freely:latest-arm64v8
          docker push nephatrine/write-freely:latest-arm64v8
          docker rmi nephatrine/write-freely:latest-arm64v8
  publish_manifest:
    needs: [publish_amd64, publish_i386, publish_arm64]
    runs-on: nephnet
    steps:
      - name: Check Base Image
        if: gitea.event_name == 'schedule'
        uses: https://github.com/lucacome/docker-image-update-checker@v1
        id: checkbase
        with:
          base-image: nephatrine/alpine-s6:latest
          image: nephatrine/write-freely:latest
          platforms: linux/amd64
      - name: Docker Login
        uses: https://github.com/docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Docker Manifest
        run: |
          docker manifest create nephatrine/write-freely:0.14.0 --amend nephatrine/write-freely:latest-amd64 --amend nephatrine/write-freely:latest-i386 --amend nephatrine/write-freely:latest-arm64v8
          docker manifest create nephatrine/write-freely:0.14 --amend nephatrine/write-freely:latest-amd64 --amend nephatrine/write-freely:latest-i386 --amend nephatrine/write-freely:latest-arm64v8
          docker manifest create nephatrine/write-freely:0 --amend nephatrine/write-freely:latest-amd64 --amend nephatrine/write-freely:latest-i386 --amend nephatrine/write-freely:latest-arm64v8
          docker manifest create nephatrine/write-freely:latest --amend nephatrine/write-freely:latest-amd64 --amend nephatrine/write-freely:latest-i386 --amend nephatrine/write-freely:latest-arm64v8
          docker manifest push --purge nephatrine/write-freely:0.14.0
          docker manifest push --purge nephatrine/write-freely:0.14
          docker manifest push --purge nephatrine/write-freely:0
          docker manifest push --purge nephatrine/write-freely:latest
      - name: Notify Discord
        if: gitea.event_name != 'schedule' || steps.checkbase.outputs.needs-updating == 'true'
        uses: https://github.com/sarisia/actions-status-discord@v1
        with:
          title: "DockerHub: write-freely"
          description: "The container image was pushed to [DockerHub](https://hub.docker.com/repository/docker/nephatrine/write-freely/general).\nPull `nephatrine/write-freely:latest` for the newest image."
          nodetail: true
          webhook: ${{ secrets.DISCORD_WEBHOOK_PACKAGE }}
      - name: Checkout Repository
        uses: https://gitea.com/actions/checkout@v3
      - name: Docker Describe
        uses: https://github.com/peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: nephatrine/write-freely
