#!/command/with-contenv /bin/sh
# SPDX-FileCopyrightText: 2023-2025 Daniel Wolf <nephatrine@gmail.com>
# SPDX-License-Identifier: ISC

# shellcheck shell=sh

export HOME=/mnt/config/home

cd /mnt/config/home || exit 1

if [ ! -d /var/www/writefreely-live ]; then
  /bin/mkdir -p /var/www/writefreely-live
  /bin/chown guardian:users /var/www/writefreely-live
fi
if [ ! -d /mnt/config/www/writefreely/pages ]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/www/writefreely/pages
fi
if [ ! -d /mnt/config/www/writefreely/static ]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/www/writefreely/static
fi
if [ ! -d /mnt/config/www/writefreely/templates ]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/www/writefreely/templates
fi
if [ -d /var/www/writefreely-live ]; then
  /command/s6-setuidgid guardian /bin/cp -R /var/www/writefreely/. /var/www/writefreely-live/
  if [ -d /mnt/config/www/writefreely ]; then
    /command/s6-setuidgid guardian /bin/cp -R /mnt/config/www/writefreely/. /var/www/writefreely-live/
  fi
fi

if [ ! -d /mnt/config/etc ]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/etc
fi
if [ -d /mnt/config/etc ]; then
  if [ ! -f /mnt/config/etc/writefreely.ini ]; then
    /command/s6-setuidgid guardian /bin/cp /etc/writefreely.ini /mnt/config/etc/writefreely.ini
  fi
  /command/s6-setuidgid guardian /bin/cp /etc/writefreely.ini.sample /mnt/config/etc/writefreely.ini.sample
fi

if [ ! -d /mnt/config/data/keys ]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/data/keys
fi
if [ ! -f /mnt/config/data/keys/cookies_auth.aes256 ] && [ -d /mnt/config/data/keys ]; then
  /command/s6-setuidgid guardian /usr/bin/writefreely -c /mnt/config/etc/writefreely.ini --gen-keys
fi

if [ -f /mnt/config/data/writefreely.db ]; then
  /usr/bin/find /mnt/config/data/ -maxdepth 1 -type f -name 'writefreely.backup-*.db' -print0 | /usr/bin/xargs -r0 /bin/ls -t | /usr/bin/tail -n +3 | /usr/bin/tr '\n' '\0' | /usr/bin/xargs -r0 /bin/rm
  /command/s6-setuidgid guardian /bin/cp -n /mnt/config/data/writefreely.db "/mnt/config/data/writefreely.backup-$(/bin/date +%Y%M%d%H%M).db"
fi

if [ -f /mnt/config/data/keys/cookies_auth.aes256 ] && [ ! -f /mnt/config/data/writefreely.db ]; then
  /command/s6-setuidgid guardian /usr/bin/writefreely -c /mnt/config/etc/writefreely.ini --init-db
  if [ -f /mnt/config/data/writefreely.db ]; then
    /bin/echo "${WRITEFREELY_VERSION}" | /command/s6-setuidgid guardian /usr/bin/tee /mnt/config/data/version
  elif [ -f /mnt/config/data/version ]; then
    /bin/rm /mnt/config/data/version
  fi
fi

if [ -f /mnt/config/data/version ]; then
  if [ "$(/bin/cat /mnt/config/data/version)" != "${WRITEFREELY_VERSION}" ]; then
    echo "Database Version Mismatch - Starting Migration"
    /command/s6-setuidgid guardian /bin/cp -n /mnt/config/data/writefreely.db "/mnt/config/data/writefreely.migrate-v$(/bin/cat /mnt/config/data/version)-v${WRITEFREELY_VERSION}.db" \
     && /command/s6-setuidgid guardian /usr/bin/writefreely -c /mnt/config/etc/writefreely.ini db migrate \
     && /bin/echo "${WRITEFREELY_VERSION}" | /command/s6-setuidgid guardian /usr/bin/tee /mnt/config/data/version
  fi
fi

if [ -f /mnt/config/data/writefreely.db ]; then
  exec /command/s6-setuidgid guardian /usr/bin/writefreely -c /mnt/config/etc/writefreely.ini
else
  /bin/echo "** no DATABASE exists **"
  /bin/sleep 300
  exit 0
fi
