#!/bin/bash

export HOME=/mnt/config/home

if [[ ! -d /mnt/config/www/writefreely/static ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/www/writefreely/static
fi
/command/s6-setuidgid guardian /bin/cp -Rn /var/www/writefreely/static/. /mnt/config/www/writefreely/static/

if [[ ! -d /mnt/config/www/writefreely/pages ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/www/writefreely/pages
fi
/bin/mkdir -p /var/www/writefreely/pages
/bin/cp -R /var/www/writefreely/default-pages/. /var/www/writefreely/pages/
/bin/cp -R /mnt/config/www/writefreely/pages/. /var/www/writefreely/pages/

if [[ ! -d /mnt/config/www/writefreely/templates ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/www/writefreely/templates
fi
/bin/mkdir -p /var/www/writefreely/templates
/bin/cp -R /var/www/writefreely/default-templates/. /var/www/writefreely/templates/
/bin/cp -R /mnt/config/www/writefreely/templates/. /var/www/writefreely/templates/

if [[ ! -f /mnt/config/etc/writefreely/config.ini ]]; then
  if [[ ! -d /mnt/config/etc/writefreely ]]; then
    /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/etc/writefreely
  fi
  /command/s6-setuidgid guardian /bin/cp /etc/writefreely.ini /mnt/config/etc/writefreely/config.ini
fi
/command/s6-setuidgid guardian /bin/cp /etc/writefreely.ini.sample /mnt/config/etc/writefreely/config.ini.blank

cd /mnt/config/etc/writefreely/

if [[ -f /mnt/config/etc/writefreely/config.ini && ! -f /mnt/config/data/keys/cookies_auth.aes256 ]]; then
  if [[ ! -d /mnt/config/data/keys ]]; then
    /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/data/keys
  fi
  /command/s6-setuidgid guardian /usr/bin/writefreely -c /mnt/config/etc/writefreely/config.ini --gen-keys
fi

if [[ -f /mnt/config/data/writefreely.db ]]; then
  /command/s6-setuidgid guardian /bin/cp /mnt/config/data/writefreely.db /mnt/config/data/writefreely.db.bak
fi
if [[ -f /mnt/config/data/keys/cookies_auth.aes256 && ! -f /mnt/config/data/writefreely.db ]]; then
  /command/s6-setuidgid guardian /usr/bin/writefreely -c /mnt/config/etc/writefreely/config.ini --init-db
  if [[ -f /mnt/config/data/writefreely.db ]]; then
    echo "${WRITEFREELY_VERSION}" | /command/s6-setuidgid guardian /usr/bin/tee /mnt/config/data/version
  elif [[ -f /mnt/config/data/version ]]; then
    rm /mnt/config/data/version
  fi
fi

if [[ -f /mnt/config/data/writefreely.db ]]; then
  /command/s6-setuidgid guardian /usr/bin/writefreely -c /mnt/config/etc/writefreely/config.ini
else
  sleep 60
fi
